name: "alexdelrio3.github.io"
title: "Investigación crítica y participativa"
description: "Bitácora de Alex del Río"
output_dir: "_site"
base_url: "/alexdelrio3.github.io"
navbar:
  right:
    - text: "Inicio"
      href: index.html
    - text: "Sobre mí"
      href: about.html
    - text: "Blog"
      href: welcome.html
    - text: "Proyectos"
      href: proyectos_index.html
    - text: "Publicaciones"
      href: publicaciones_index.html
    - text: "Recursos"
      href: recursos_index.html
    - text: "Datos abiertos"
      href: datos_abiertos.html
output: 
  distill::distill_article:
    css: style.css
