name: "alexdelrio3.github.io"
title: "Investigación crítica y ciencia abierta"
description: "Bitácora de Alex del Río"
output_dir: "_site"
base_url: "/alexdelrio3.github.io"
navbar:
  right:
    - text: "Inicio"
      href: index.html
    - text: "Sobre mí"
      href: about.html
    - text: "Blog"
      href: posts/index.html
    - text: "Proyectos"
      href: proyectos/index.html
    - text: "Publicaciones"
      href: publicaciones/index.html
    - text: "Recursos"
      href: recursos/index.html
    - text: "Datos abiertos"
      href: datos_abiertos/index.html
output: 
  distill::distill_article:
    css: style.css
